version: '3.8'

services:
  # Aplicação Principal
  app:
    build: .
    container_name: xunimpay-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/xunimpay
      - SPRING_DATASOURCE_USERNAME=xunim
      - SPRING_DATASOURCE_PASSWORD=xunim123
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@mongodb:27017/xunimpay_audit?authSource=admin
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PASSWORD=redis123
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=admin
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - xunimpay-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health/simple"]
      timeout: 20s
      retries: 5
      interval: 30s
      start_period: 60s

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: xunimpay-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xunimpay
      MYSQL_USER: xunim
      MYSQL_PASSWORD: xunim123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s
    networks:
      - xunimpay-network
    restart: unless-stopped

  # MongoDB
  mongodb:
    image: mongo:7
    container_name: xunimpay-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: xunimpay_audit
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init.js
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      timeout: 20s
      retries: 5
      interval: 30s
      start_period: 30s
    networks:
      - xunimpay-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: xunimpay-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      timeout: 20s
      retries: 5
      interval: 30s
      start_period: 10s
    networks:
      - xunimpay-network
    restart: unless-stopped

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: xunimpay-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: xunimpay
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      timeout: 20s
      retries: 5
      interval: 30s
      start_period: 30s
    networks:
      - xunimpay-network
    restart: unless-stopped

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: xunimpay-elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=xunimpay-cluster
      - node.name=xunimpay-node
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s || exit 1"]
      timeout: 20s
      retries: 5
      interval: 30s
      start_period: 60s
    networks:
      - xunimpay-network
    restart: unless-stopped

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: xunimpay-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      SERVER_NAME: kibana.xunimpay.local
      SERVER_PUBLICBASEURL: http://localhost:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:5601/api/status || exit 1"]
      timeout: 20s
      retries: 5
      interval: 30s
      start_period: 60s
    networks:
      - xunimpay-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
    name: xunimpay_mysql_data
  mongodb_data:
    driver: local
    name: xunimpay_mongodb_data
  redis_data:
    driver: local
    name: xunimpay_redis_data
  rabbitmq_data:
    driver: local
    name: xunimpay_rabbitmq_data
  elasticsearch_data:
    driver: local
    name: xunimpay_elasticsearch_data

networks:
  xunimpay-network:
    driver: bridge
    name: xunimpay-network