# Config
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: xunimpay-payment-system

  profiles:
    active: dev

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Mongodb Configuration
  mongodb:
    database: xunimpay-audit

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      password: redis123

  # Security Configuration
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Logging
logging:
  level:
    com.xunim: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"